// <auto-generated />
using Labb_4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_4.Models.Hobby", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hobbys");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Loves to go to car meets as well as car shows",
                            HobbyName = "Cars"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Nothing beats fishing with a nice summerbreeze",
                            HobbyName = "Fishing"
                        },
                        new
                        {
                            ID = 3,
                            Description = "There's something satisfying with building computers",
                            HobbyName = "Computers"
                        },
                        new
                        {
                            ID = 4,
                            Description = "What a way to relax when reading a book and earn knowledge",
                            HobbyName = "Books"
                        });
                });

            modelBuilder.Entity("Labb_4.Models.Link", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HobbyID")
                        .HasColumnType("int");

                    b.Property<string>("LinkName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HobbyID");

                    b.HasIndex("PersonID");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            HobbyID = 1,
                            LinkName = "SchmiedMann",
                            PersonID = 1,
                            URL = "https://www.schmiedmann.se/"
                        },
                        new
                        {
                            ID = 2,
                            HobbyID = 2,
                            LinkName = "Fiske",
                            PersonID = 2,
                            URL = "https://www.fiske.se/"
                        },
                        new
                        {
                            ID = 3,
                            HobbyID = 3,
                            LinkName = "Komplett",
                            PersonID = 3,
                            URL = "https://www.komplett.se/"
                        },
                        new
                        {
                            ID = 4,
                            HobbyID = 4,
                            LinkName = "AkademiBokHandeln",
                            PersonID = 4,
                            URL = "https://www.akademibokhandeln.se/"
                        },
                        new
                        {
                            ID = 5,
                            HobbyID = 1,
                            LinkName = "SchmiedMann",
                            PersonID = 5,
                            URL = "https://www.schmiedmann.se/"
                        },
                        new
                        {
                            ID = 6,
                            HobbyID = 2,
                            LinkName = "Fiske",
                            PersonID = 6,
                            URL = "https://www.fiske.se/"
                        },
                        new
                        {
                            ID = 7,
                            HobbyID = 3,
                            LinkName = "Komplett",
                            PersonID = 7,
                            URL = "https://www.komplett.se/"
                        },
                        new
                        {
                            ID = 8,
                            HobbyID = 4,
                            LinkName = "AkademiBokHandeln",
                            PersonID = 8,
                            URL = "https://www.akademibokhandeln.se/"
                        });
                });

            modelBuilder.Entity("Labb_4.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Dennis",
                            Phone = "0743884618"
                        },
                        new
                        {
                            ID = 2,
                            Name = "John",
                            Phone = "0742143245"
                        },
                        new
                        {
                            ID = 3,
                            Name = "King",
                            Phone = "0743453447"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Thomas",
                            Phone = "0756756467"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Igor",
                            Phone = "0767456446"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Affe",
                            Phone = "0744564472"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Vivien",
                            Phone = "0713454565"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Cecilia",
                            Phone = "0746867285"
                        });
                });

            modelBuilder.Entity("Labb_4.Models.Link", b =>
                {
                    b.HasOne("Labb_4.Models.Hobby", "Hobby")
                        .WithMany()
                        .HasForeignKey("HobbyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_4.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
